---
apiVersion: v1
kind: Pod
metadata:
  name: basicpod
  labels:
    type: webserver
spec:
  containers:
  - name: webcont
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 10m
        memory: 20Mi
      requests:
        cpu: 10m
        memory: 20Mi
    volumeMounts:
    - mountPath: "/var/log/nginx/"  #
      name: weblog-pv-storage       # Must match volume name above
  - name: fdlogger
    image: fluent/fluentd
    ports:
    - containerPort: 80
    env:                              #Same depth as image:
    - name: FLUENTD_ARGS
      value: -c /etc/fluentd-config/fluentd.conf
    resources:
      limits:
        cpu: 10m
        memory: 20Mi
      requests:
        cpu: 10m
        memory: 20Mi
    volumeMounts:                     #<--Same depth as image:
    - mountPath: "/var/log"         # We will configure this directory soon
      name: weblog-pv-storage       # Must match volume name above
    - name: log-config              # Must match volume name above
      mountPath: "/etc/fluentd-config"
---
apiVersion: v1
kind: Service
metadata:
  name: basicservice
  labels:
    type: webserver
spec:
  selector:
    type: webserver
  type: NodePort
  ports:
  - protocol: TCP
    port: 80