---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weblog-pv-claim
spec:
  # storageClassName: logging
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


# kubectl apply -f /Users/ivanka/code/self/kubernetes-trainings/lfd259-k8s-developer/labs/lab5/pvc-weblog.yaml
# kubectl delete -f /Users/ivanka/code/self/kubernetes-trainings/lfd259-k8s-developer/labs/lab5/pvc-weblog.yaml
# kubectl describe pvc weblog-pv-claim