---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: reporing-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: reporting-tool
            image: reporting-tool
          restartPolicy: Never
      backoffLimit: 4
      completions: 3
      parallelism: 3
