---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_HOST: aG9zdC50ZXN0
  DB_USERNAME: ZGIudXNlcm5hbQ==
  DB_PASSWROD: ZGIucGFzc3dvcmQ=
---
apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
  labels:
    name: simple-webapp-color
spec:
  containers:
  - name: simple-webapp-color
    image: simple-webapp-color
    ports:
    - containerPort: 8080
    env:
    - name: DB_PASSWROD
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: DB_PASSWROD
    envFrom:
    - secretRef:
        name: app-secret